[package]
name = "rpi-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tide = "^0.16.0"
async-std = { version = "^1.13.0", features = ["attributes"] }
serde = { version = "^1.0", features = ["derive"] }
rand = "0.9.2"